name: Docker Image CI

on:
  workflow_dispatch:
 # push:
 #   branches: [ "master" ]
 # pull_request:
 #   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Set current date and time
      run: echo "tag_time=$(date +%s)" >> .env

      
    - name: Build  the Docker image 
      run: |
         source .env
         echo $tag_time
         docker build . --file Dockerfile --tag  sureshkodati/do_demo:$tag_time
         #docker tag  do_demo:${{ env.tag_time }} sureshkodati/do_demo:$tag_time
    - name: list files
      run: |
        set -ex
        cd target
        #ls
        docker images
      
    - name: Push image to docker hub
      run: |
         source .env
         echo $tag_time
         docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }}
         echo $?
         docker push sureshkodati/do_demo:$tag_time
      
